### PR TITLE
Fix hard links

### LINKED ISSUE #152: Broken on win32
## What version of the package or command are you using?
`bfece90dc3bb7199e8a397a27eb267a6cdd9589c`

## What are you trying to do?
Extract [Git-2.11.0.3-32-bit.tar.bz2](https://github.com/git-for-windows/git/releases/download/v2.11.0.windows.3/Git-2.11.0.3-32-bit.tar.bz2) on Windows 7 32 bit edition

## What steps did you take?
See [task definition](https://tools.taskcluster.net/groups/Wz1hd0EJRMCgO06WipokRQ/tasks/Ho2J-QK4Reay9mnUEDLXiw/details):

1) Downloaded [Git-2.11.0.3-32-bit.tar.bz2](https://github.com/git-for-windows/git/releases/download/v2.11.0.windows.3/Git-2.11.0.3-32-bit.tar.bz2) as `git.tar.bz2`

2) Extracted it successfully with archiver version 2.1:

```
archiver.exe open git.tar.bz2 git
```

3) Built from master branch revision `bfece90dc3bb7199e8a397a27eb267a6cdd9589c`
4) Tried to extract with version 3 `arc unarchive git.tar.bz2 git2`

## What did you expect to happen, and what actually happened instead?

I expected the extraction to be successful. But I got [errors](https://taskcluster-artifacts.net/Ho2J-QK4Reay9mnUEDLXiw/0/public/logs/live_backing.log):

```
Z:\task_1551972425>arc unarchive git.tar.bz2 git2 
2019/03/07 15:37:07 [ERROR] Reading file in tar archive: git2\git\mingw32\bin\git-upload-archive.exe: making hard link for: link git2\git\mingw32\bin\git-upload-archive.exe\mingw32\bin\git-receive-pack.exe git2\git\mingw32\bin\git-upload-archive.exe: The system cannot find the path specified.
2019/03/07 15:37:10 [ERROR] Reading file in tar archive: git2\git\mingw32\libexec\git-core\git.exe: making hard link for: link git2\git\mingw32\libexec\git-core\git.exe\mingw32\bin\git.exe git2\git\mingw32\libexec\git-core\git.exe: The system cannot find the path specified.
2019/03/07 15:37:10 [ERROR] Reading file in tar archive: git2\git\mingw32\libexec\git-core\git-add.exe: making hard link for: link git2\git\mingw32\libexec\git-core\git-add.exe\mingw32\bin\git-receive-pack.exe git2\git\mingw32\libexec\git-core\git-add.exe: The system cannot find the path specified.
2019/03/07 15:37:10 [ERROR] Reading file in tar archive: git2\git\mingw32\libexec\git-core\git-am.exe: making hard link for: link git2\git\mingw32\libexec\git-core\git-am.exe\mingw32\bin\git-receive-pack.exe git2\git\mingw32\libexec\git-core\git-am.exe: The system cannot find the path specified.
2019/03/07 15:37:10 [ERROR] Reading file in tar archive: git2\git\mingw32\libexec\git-core\git-annotate.exe: making hard link for: link git2\git\mingw32\libexec\git-core\git-annotate.exe\mingw32\bin\git-receive-pack.exe git2\git\mingw32\libexec\git-core\git-annotate.exe: The system cannot find the path specified.
2019/03/07 15:37:10 [ERROR] Reading file in tar archive: git2\git\mingw32\libexec\git-core\git-apply.exe: making hard link for: link git2\git\mingw32\libexec\git-core\git-apply.exe\mingw32\bin\git-receive-pack.exe git2\git\mingw32\libexec\git-core\git-apply.exe: The system cannot find the path specified.
2019/03/07 15:37:10 [ERROR] Reading file in tar archive: git2\git\mingw32\libexec\git-core\git-archive.exe: making hard link for: link git2\git\mingw32\libexec\git-core\git-archive.exe\mingw32\bin\git-receive-pack.exe git2\git\mingw32\libexec\git-core\git-archive.exe: The system cannot find the path specified.
.....
```

## How do you think this should be fixed?
Presumably this is a regression, since we could extract the same .tar.bz file on Windows 7 32 bit edition using archiver 2.1.

## Please link to any related issues, pull requests, and/or discussion

* [Mozilla bug 1533402](https://bugzil.la/1533402) 

## Bonus: What do you use archiver for, and do you find it useful?

We import the go library at Mozilla in the worker that runs most of Mozilla's CI tasks.

### PR DESCRIPTION
**Pull request by mholt**
Had to refactor how paths/filenames are passed into some functions to accommodate hard-linked files.

@petemoore Would you please try this out?

Should fix #152.

### CODE REVIEW

**Comment by petemoore** [comment]
Hi Matt, many thanks for the quick response!

I did notice that I get slightly different results extracting the archive with version 2.1 vs this version.

See [this example task](https://tools.taskcluster.net/groups/KQ8u-KICTVmouDhPlrdhmQ/tasks/KQ8u-KICTVmouDhPlrdhmQ/details). Here I extract with archiver version 2.1 to the directory `git`:

```
archiver.exe open git.tar.bz2 git
```

Then I extract to directory `git-archiverPR153` with:

```
arc unarchive git.tar.bz2 git-archiverPR153
```

I expected that the contents of directories `git` and `git-archiverPR153` would be the same, however the `git-archiverPR153` directory contains an additional nested `git` directory, so the equivalent directories are `git` and `git-archiverPR153\git`.

See the [task log](https://taskcluster-artifacts.net/KQ8u-KICTVmouDhPlrdhmQ/0/public/logs/live_backing.log) for more context. Thanks!

**Comment by mholt** [comment]
Okay, thanks for checking. I won't have time to revisit this for a while, but patches are welcome and I can incorporate it into this PR!

**Comment by gus** [comment]
@mholt if you grab the latest commit from the [`fix-hardlinks`](https://github.com/ActiveState/archiver/tree/fix-hardlinks) branch of the ActiveState fork, you'll see we've fixed the `Tar.Extract` function and added some tests.

I can only verify that this fix works on my setup:

**Comment by mholt** [comment]
@gus Great, thanks! Love the tests.

@petemoore Would you be able to test with Gus' patch as well, and if it works, we'll bring it in.

**Comment by mholt** [comment]
Is this still a needed change?

**Comment by petemoore** [comment]
@mholt, apologies, I had missed the updates on this. I will try to check this week if this fixes things for us, and get back to you! Many thanks for reacting so quickly to the issue, and sorry for not getting back to you sooner.

**Comment by klutchell** [comment]
I'm still hoping for this merge!

**Comment by mholt** [comment]
@petemoore @klutchell @gus Can y'all check out #171 and verify that it works for you? If so, I am going to merge that.

**Comment by klutchell** [comment]
works on my end!

**Comment by mholt** [comment]
That's good enough for me, then, after about 6 months. :P Merged that one, obsoleting this one. Thanks!

**Comment by klutchell** [comment]
Was this merged to master? It looks like it just went to the `fix-hardlinks` branch.

**Comment by petemoore** [comment]
See https://github.com/mholt/archiver/pull/171#issuecomment-588129903 - I think maybe this never reached `master` branch.

**Pull request closed without merging**
