### PR TITLE
Continuous fuzzing

### PR DESCRIPTION
**Pull request by bookmoons**
Hi guys. What would you think about integrating fuzzing? Opening this as a draft PR to show what it looks like and invite discussion. [Fuzzit](https://fuzzit.dev/) gives free service to open source.

This patch fuzzes `Zip.Unarchive()` and `Lz4.DecompressFile()`. A local run found an archive that crashes Zip. I'll post it in a comment. There's a successful run on Travis:
https://travis-ci.org/bookmoons/archiver/builds/575667464

If it's interesting I can run through the rest of the archivers and compressors.

### CODE REVIEW

**Comment by bookmoons** [comment]
Here's the crash data. It's 3 files in an archive. The unsuffixed file is the crashing input.

[6ed4b56b97d2bca199fe0cc7ddf5a0be09e74cb6.zip](https://github.com/mholt/archiver/files/3532907/6ed4b56b97d2bca199fe0cc7ddf5a0be09e74cb6.zip)

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8913fa]

goroutine 1 [running]:
github.com/mholt/archiver.(*Zip).Walk(0xc000073260, 0x96002d, 0x10, 0x9744e0, 0x0, 0x0)
	/home/user/go/src/github.com/mholt/archiver/zip.go:439 +0x19a
github.com/mholt/archiver.Walk(0x96002d, 0x10, 0x9744e0, 0x1ac83, 0x1ac83)
	/home/user/go/src/github.com/mholt/archiver/archiver.go:223 +0x270
github.com/mholt/archiver.FuzzZip(0x7c894c33b000, 0x1ac83, 0x1ac83, 0x3)
	/home/user/go/src/github.com/mholt/archiver/archiver_fuzz.go:14 +0xd9
go-fuzz-dep.Main(0xc000097f78, 0x2, 0x2)
	/tmp/go-fuzz-build529970951/goroot/src/go-fuzz-dep/main.go:36 +0x1b6
main.main()
	/tmp/go-fuzz-build529970951/gopath/src/github.com/mholt/archiver/go.fuzz.main/main.go:17 +0x5d
exit status 2
```

**Comment by bookmoons** [comment]
[`go-fuzz-corpus`](https://github.com/dvyukov/go-fuzz-corpus) also has a nice set of corpuses for some of these formats. Could be used to seed them.

**Comment by mholt** [comment]
I think fuzzing is great, and thanks for the draft PR, but, wouldn't it be more effective/proper to fuzz the actual libraries that do the work? Archiver is just glue to bring those various libraries into one convenient package & command.

**Comment by bookmoons** [comment]
Makes sense. Thanks for looking at it.

**Pull request closed without merging**
