### PR TITLE
all: split zip out into subpackage

### PR DESCRIPTION
**Pull request by kevinburke1**
Building on the discussion in #180, this is a way for callers to be
able to use the zip package directly without importing the other
compression/decompression packages. It uses aliases to preserve
backwards compatibility.

The utility functions and types used by the zip package needed to
be split out into a subpackage as well (named "common") to avoid a
circular dependency issue.

### CODE REVIEW

**Comment by Jacalz** [comment]
I think this is a great change to make. Just want to give a friendly heads up that the tests seem to be failing on the PR.

**Comment by kevinburkemeter** [comment]
Looking, thanks.

**Comment by kevinburkemeter** [comment]
I can reproduce _an_ test failure locally but just a heads up that I don't have permission to view the Azure build logs.

**Comment by kevinburkemeter** [comment]
Tests fixed! And also made the PR up to date.

**Review by Jacalz — CHANGES_REQUESTED** [review]
Sorry, but this would need to be rebased on the work in https://github.com/mholt/archiver/commit/699ca560fed0e13b9c0639b01e372f19816ccc8c, to use github.com/klauspost/compress/zip for the zip handling. It is also out of date with the master branch.

Hopefully @mholt can review this once that is fixed :slightly_smiling_face:

**Comment by kevinburkemeter** [comment]
Please check it now

**Comment by mholt** [comment]
Thanks, I will review when I have a chance! Currently pretty focused on another project.

**Comment by Jacalz** [comment]
I will make sure to test this as well when I get some time to do so. Will be interesting to see how the binary size is affected.

**Review by Jacalz — APPROVED** [review]
Nice work! This looks good to me. I am seeing around a 0.5MB decrease in binary size when using this over the standard `archiver` package (Go1.15 on Linux). Not massive, but a good step in the right direction :slightly_smiling_face:

**Comment by Jacalz** [comment]
We should probably move all the different formats out to their own packages, but this is a great step on the way there :slightly_smiling_face:

**Comment by mholt** [comment]
Hey, thanks for this PR. I remember I just commented again on the related issue today. It's not a change I feel compelled to make quite yet, but if more compelling use cases / requests come in for it, I might be willing to consider it.

Closing, as this PR is obsoleted by #302, which has true "plugin" support for the formats. So if we do decide to do it, it should be a little easier.

**Pull request closed without merging**
