### PR TITLE
Add KeepParentDirectories flag 

### PR DESCRIPTION
**Pull request by chriswalz**
**When zipping something like this the paths were mapping like:**

web/static -> static
configs/os_agnostic/deployment -> deployment

**I want something like this**

web/static -> web/static
configs/os_agnostic/deployment -> configs/os_agnostic/deployment

### CODE REVIEW

**Comment by chriswalz** [comment]
Any thoughts on this?

**Comment by mholt** [comment]
Can you be more specific about what you are doing, what the actual behavior is, and what the expected behavior is?

**Comment by chriswalz** [comment]
**Background**

I wrote a go server that has html files stored in a folder `web/html`. The server uses this path to find the html files that it serves. 

When I zip these files and copy them to a linux server in the cloud and unzip them the path is now just `html` (The parent folder `web` no longer exists). Now when my server tries to serve files from `web/html` it thinks they don't exist since they're really in `html` folder. 

I hope that's more clear. 

**Actual Behavior**

web/html -> html

**Expected (with `KeepParentDirectories` flag)** 

web/html -> web/html

**Comment by chriswalz** [comment]
Also, note I originally had a bash script that was using mac terminal `zip` and `unzip`. 

When I converted this script to Go, using `Archiver` package it wasn't working anymore since `zip`'s output is different than `Archiver`'s with the same parameters hence why I'm suggesting adding this flag. 

Perhaps I'm missing something and one of the other flags do this but it doesn't appear to be so.

**Comment by mholt** [comment]
I _almost_ understand, but if you could provide a few lines of code (or the exact commands you're using, if the CLI) to demonstrate what you mean, that would be best.

**Comment by chriswalz** [comment]
Expected behavior using (`zip` and `unzip`)
expected

Actual behavior using (`arc archive` and `unzip`)
actual

**Comment by mholt** [comment]
Awesome, thank you!

**Comment by chriswalz** [comment]
So can we merge it in? What's the next step

**Comment by mholt** [comment]
I just need to find some time to review it. Sorry, it's on me.

**Comment by mholt** [comment]
v4, introduced in #302, gives you this flexibility now, so I think this is resolved/irrelevant in the new version.

**Pull request closed without merging**
