### PR TITLE
Add dereference option to FilesFromDisk

### PR DESCRIPTION
**Pull request by korpa**
This is a first suggestion how this feature could look like.

Solves #303

### CODE REVIEW

**Review by mholt — CHANGES_REQUESTED** [review]
Nice, thanks for the implementation.

I think the API for this could be improved. How about if we keep just the one function, `FilesFromDisk()`, where the first argument is a struct of options for assembling the list of files? The only option for now would be whether to follow symlinks.

**Comment by korpa** [comment]
I had the same idea, but I didn't want to change parameters for `FilesFromDisk()` to not break the function.

**Comment by mholt** [comment]
I wouldn't worry about that. V4 is in alpha so it is still under active development. Breaking changes are allowed and expected, I've already broken the v4 API a few times this week.

**Comment by korpa** [comment]
I will have no time until the weekend for this. So please go ahead. If you haven't done it till Saturday, I will jump in.

**Comment by mholt** [comment]
@korpa No worries. I just pushed my version of the change. What do you think? Let me know if you have a chance to try it.

**Comment by mholt** [comment]
I think I'll probably merge this today and tag a new alpha version, if you have a chance to check it out you can!

**Comment by korpa** [comment]
Please let me know, as soon as you have the new alpha out.

**Comment by mholt** [comment]
@korpa Will do. Do you want to test this first to make sure it does what you want?

**Comment by korpa** [comment]
Looks very good. I replaced my personal "filesFromDisk" function with `files, err := archiver.FilesFromDisk(archiver.FromDiskOptions{FollowSymlinks: true}, filesDirs)`, created my tar.gz and extracted it

=> Instead of a symlink there was a file with the content as expected.

**Comment by korpa** [comment]
Before creating a new alpha should we add some info in the README?

**Review by mholt — APPROVED** [review]
Awesome, thank you for testing!!

I will merge this, update the README, and tag a new alpha release.

**Comment by mholt** [comment]
@korpa Here is the tag, and I updated the readme: https://github.com/mholt/archiver/releases/tag/v4.0.0-alpha.3

I also made the options parameter optional (by making it a pointer). See the godoc :+1: Thanks again!

**Comment by korpa** [comment]
alpha3 works as expected as well after changing the options parameter to a pointer. 

Thank you very much for adding this feature.

**Comment by mholt** [comment]
Great! And thank you for the initial PR.

**Pull request merged**
