### PR TITLE
Remove bundling of GoLangCI Lint as a dependency.

### PR DESCRIPTION
**Pull request by fergusstrange**
Currently the entirety of https://github.com/golangci is imported. It appears this is actually only used within the build phase of archiver and should not be bundled as a dependency.

This PR removes it as a dependency and installs it as a binary during build, significantly reducing the dependency footprint.

### CODE REVIEW

**Comment by fergusstrange** [comment]
This relates to issues https://github.com/mholt/archiver/issues/244

**Comment by coolaj86** [comment]
Looks good to me. I'll test it myself and merge it in. Thanks.

**Comment by fergusstrange** [comment]
Great thanks @coolaj86.

**Review by coolaj86 — APPROVED** [review]
LGTM

**Pull request merged**
