### PR TITLE
Add double-evil.tar, double-evil.zip, create-evil-tar.go and create-evil-zip.go

### PR DESCRIPTION
**Pull request by kross9924**
Add double-evil.tar and double-evil.zip inside testdata/testarchives/evilarchives

Add create-evil.tar.go and create-evil.zip.go inside testdata

### CODE REVIEW

**Comment by kross9924** [comment]
@coolaj86 please check this.

**Comment by coolaj86** [comment]
Looks great! Thank you.

**Comment by coolaj86** [comment]
The zip file works as expected, I just tested.

Something is wrong with the tar file. I'm looking into it.

**Review by coolaj86 — APPROVED** [review]

**Comment by coolaj86** [comment]
@kross9924 I made a few edits and now it creates a proper tar file. I'm not sure if the issue was with the header type or the file mode, but it seems one of the two fixed it.

**Comment by kross9924** [comment]
Thank You

**Pull request merged**
