### PR TITLE
Add github actions for CI (#297)

### PR DESCRIPTION
**Pull request by iotanbo**
This PR adds Github Actions support to the project, related issue is [#297](https://github.com/mholt/archiver/issues/297).

### CODE REVIEW

**Review by mholt — APPROVED** [review]
This looks great, thanks. Can we remove the azure CI while we're at it?

**Comment by iotanbo** [comment]
Removed `azure-pipelines.yml` and the badge from README.md.
If there are any references to azure that I omitted, let me know.

**Review by mholt — APPROVED** [review]
Excellent, thank you! I had been wanting to get around to this but, life....

**Comment by iotanbo** [comment]
Cool, btw what do you think about a new patch release?

**Comment by mholt** [comment]
Done

**Pull request merged**
