### PR TITLE
Add TypeGNUSparse as tar type to handle vmdk,qcow2 images

### PR DESCRIPTION
**Pull request by praveenkumar**
Fix issue #165 

Add the go modules

### CODE REVIEW

**Comment by gbraad** [comment]
Works for me

**Comment by gbraad** [comment]
Note: `GO111MODULE=auto` is set and fails the build

**Comment by cfergeau** [comment]
This really is  about the use of -S/--sparse when generating the tarball (and adding a sparse file to it), this not related to vmdk, qcow2 or gz vs xz (I was initially misled by the commit logs :)

**Comment by mholt** [comment]
Closing due to inactivity; will add the flag in a separate commit.

**Pull request closed without merging**
