### PR TITLE
fix: referencing symbolic links with tar archive

### PR DESCRIPTION
**Pull request by jbrockopp**
Fixes https://github.com/mholt/archiver/issues/202

**NOTE: Essentially this is a copy of https://github.com/mholt/archiver/pull/201**

Intended to resolve the issue submitted in the original PR 👍 

The only difference should be this PR also has tests as it was stated the original change won't be accepted without them:

https://github.com/mholt/archiver/pull/201#issuecomment-613647397

Please let us know if anything else is required.

### CODE REVIEW

**Comment by coolaj86** [comment]
Hey @jbrockopp @ganeshrvel @technicianted  @nishant-handa @kneal!

I've been given the almighty approver status and I'd like to help get this symlink fixed pushed through in the next day or two. There's just a few things I'd like to get from you to understand this better:

1. Can you add a symlink to the `testdata/corpus` folder that demonstrates the problem?
2. Can you give me the output of `tree` or [`lsd --tree --icon=never`](https://webinstall.dev/lsd) on a directory structure that demonstrates the problem? I expect that should look something like this:
     ```
    testdata
    ├── gnu-hardlinks.tar
    ├── sample.rar
    └── corpus
       ├── already-compressed.jpg
       ├── quote1.txt
       └── proverbs
          ├── proverb1.txt
          ├── proverb2-symlink.txt ⇒ proverb2.txt
          ├── proverb2.txt
          └── extra
             └── proverb3.txt
    ```
3. Will you `git rebase master; git push --force` to update the commit to the latest master and trigger the CI/CD ( which I just fixed in #234 ) to kick off again?

If you can do that for me, I should be able to merge this in right away and get it released this week.

**Comment by jbrockopp** [comment]
@coolaj86 apologies on getting back to you so late!

I actually completely missed your feedback and a colleague pointed it out today 😅 

To start, you requested I rebase with master and as of today (12/30/2020), I believe all commits have been pulled in.

For the sake of transparency, here is a link to our forked repo where that change was submitted:

https://github.com/go-vela/archiver/pull/2

The accompanying commit in this PR for that change can be found here:

https://github.com/mholt/archiver/pull/230/commits/ec598a968f77de02c6a21038bf50da31288d8273

You also asked if I could add a symlink in the `testdata/corpus` folder so here is the commit for that:

https://github.com/mholt/archiver/pull/230/commits/00a7841d986163ef8fc44a901ecbe57139edb019

It appears that after adding that symlink file, it has made some tests fail that appear outside my changes?

This makes me want to remove it from `testdata/corpus` but I'll wait for confirmation from you 👍 

Here is what the output for `tree` looks like now:

```sh
$ tree testdata/corpus
testdata/corpus
├── already-compressed.jpg
├── proverbs
│   ├── extra
│   │   └── proverb3.txt
│   ├── proverb1.txt
│   ├── proverb2-symlink.txt -> proverb2.txt
│   └── proverb2.txt
└── quote1.txt

2 directories, 6 files
```

FWIW:

In the original PR submitted, I actually added a `gnu-symlinks.tar` file that had symlinks in it with the tests:

* [Unarchive](https://github.com/mholt/archiver/blob/00a7841d986163ef8fc44a901ecbe57139edb019/tar_test.go#L68)
* [Extract](https://github.com/mholt/archiver/blob/00a7841d986163ef8fc44a901ecbe57139edb019/tar_test.go#L110)

Here is what that directory structure looks like:

```sh
$ mkdir testdata/gnu-symlinks

$ tar -xf testdata/gnu-symlinks.tar -C testdata/gnu-symlinks

$ tree testdata/gnu-symlinks
testdata/gnu-symlinks
└── dir-1
    └── dir-2
        ├── file-a
        ├── file-b
        ├── file-c -> file-a
        └── file-d -> file-b

2 directories, 4 files
```

This is setup based off the pre-existing `testdata/gnu-hardlinks.tar` file which has this directory structure:

```sh
$ mkdir testdata/gnu-hardlinks

$ tar -xf testdata/gnu-hardlinks.tar -C testdata/gnu-hardlinks

$ tree testdata/gnu-hardlinks
testdata/gnu-hardlinks
└── dir-1
    └── dir-2
        ├── file-a
        └── file-b

2 directories, 2 files
```

cc: @ganeshrvel @technicianted @nishant-handa @kneal

**Comment by xkisu** [comment]
Some progress needs to be made on this asap - it's severely affecting specific use cases in downstream repositories. In https://github.com/pterodactyl/wings/blob/develop/server/archiver.go it's causing server transfers to completely fail if a server has symlinks in its files - merging this patch into a fork solved the issue immediately.

**Comment by mholt** [comment]
If anyone would like to step up and pledge to help maintain this project in the long-term -- i.e. for more than just one or two PRs -- or commit to sponsor at a sufficiently high tier, that would help things move along faster. Right now my hands are full with Caddy development, unfortunately, and my current sponsors aren't really using this library, they're using Caddy.

**Comment by jbrockopp** [comment]
@coolaj86 @mholt 

I never heard back on whether or not I should remove the symlink from the `testdata/corpus` folder so I did it anyway.

As I suspected, now all status checks are passing 👍 

Similar to what @xkisu stated, we were experiencing problems using symlinks with this library:

https://github.com/go-vela/community/issues/30

So we decided to fix it ourselves and then contribute back:

https://github.com/go-vela/vela-s3-cache/pull/20

We haven't experienced any issues since then so is there any reason this can't be merged now?

Tests have been added to verify the functionality as requested in the original PR:

* https://github.com/mholt/archiver/pull/201#issuecomment-559861369
* https://github.com/mholt/archiver/pull/201#issuecomment-613647397

cc: @ganeshrvel @technicianted @nishant-handa @kneal

**Comment by mholt** [comment]
Probably fixed in #296.

**Pull request closed without merging**
